Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://unblockeds-games.com/games/happy-wheels/index.min.html
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://unblockeds-games.com/games/happy-wheels/index.min.html
UUID: 15e67633-3dae-4f6f-959e-6f99188eb2bd
Group: ""
Additional Applications: {}
