Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://happywheelsunblocked.io/happy-wheels-unblocked.embed
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://happywheelsunblocked.io/happy-wheels-unblocked.embed
UUID: 3871e5cb-97ef-4907-85af-5469f7a65a45
Group: ""
Additional Applications: {}
