Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://mathgames66.github.io/017f9003-0089-43d4-8c75-9d5e69ea0bc7/content/00g.com/uploads/b/139890129-740932336170612268/files/index.html
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://mathgames66.github.io/017f9003-0089-43d4-8c75-9d5e69ea0bc7/content/00g.com/uploads/b/139890129-740932336170612268/files/index.html
UUID: e657023f-516c-4d3b-b201-45fb7f1d84c2
Group: ""
Additional Applications: {}
