Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://games-online.io/game/HappyWheels/
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://games-online.io/game/HappyWheels/
UUID: 7bb97d88-7a66-477b-98dd-b21e75014fde
Group: ""
Additional Applications: {}
