Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://the.deconstructors.co.uk/tam-pointerlock-friendly/?url=https%3A%2F%2Ftam-shellshockers.arfotoarte.com
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://the.deconstructors.co.uk/tam-pointerlock-friendly/?url=https%3A%2F%2Ftam-shellshockers.arfotoarte.com
UUID: 4d60650d-a891-4f43-a35b-04b8472affbf
Group: ""
Additional Applications: {}
