Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://html5.gamedistribution.com/4b289f8af5e44e7a99ac9e8dd9d4b5c2/
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://html5.gamedistribution.com/4b289f8af5e44e7a99ac9e8dd9d4b5c2/
UUID: c04134bd-2aa5-465e-a69f-03ba3577e6d6
Group: ""
Additional Applications: {}
