Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://watchdocumentaries.com/wp-content/uploads/games/wordle-unlimited/
Primary Platform: Flash
Platforms: Flash; HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://watchdocumentaries.com/wp-content/uploads/games/wordle-unlimited/
UUID: 731f757a-603b-4f45-85fd-40bd6afe7598
Group: ""
Additional Applications: {}
